---

- name: Make sure python minimal is installed for ansible
  hosts: all
  gather_facts: "False"
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: "True"
      changed_when: "False"

- name: Run the base role on the instance
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  roles:
    # We're calling from the packer directory
    - { role: ../ansible/roles/common }
